[project]
authors = ["Eric Ma <ericmajinglong@gmail.com>", "Mridul Seth <seth.mridul@gmail.com>"]
channels = ["conda-forge"]
description = "Network Analysis Made Simple"
name = "Network-Analysis-Made-Simple"
platforms = ["osx-arm64", "linux-64", "win-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
jlab = "jupyter lab"

[dependencies]
python = "3.11.*"
ffmpeg = ">=7.1.0,<8"
hiveplot = ">=0.1.8.4,<0.2"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.3.4,<5"
matplotlib = ">=3.10.0,<4"
networkx = ">=3.4.2,<4"
numpy = ">=2.2.1,<3"
pandas = ">=2.2.3,<3"
pyjanitor = ">=0.30.0,<0.31"
python-louvain = ">=0.16,<0.17"
scipy = ">=1.15.1,<2"
seaborn = ">=0.13.2,<0.14"
tqdm = ">=4.67.1,<5"
pyprojroot = ">=0.3.0,<0.4"

[pypi-dependencies]
nams = { path = ".", editable = true }
[feature.docs.dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocs-material-extensions = "*"
pymdown-extensions = "*"

[feature.dev.dependencies]
pre-commit = "*"

[environments]
nams = ["docs", "dev"]
docs = ["docs"]
